import os
import re
import io
import sys
import json
import time
import math
import shutil
import hashlib
import subprocess
from dataclasses import dataclass, asdict
from typing import Dict, List, Optional, Tuple

@dataclass
class StaticFeatures:
    """
    Dataclass to hold features extracted from the static analysis of an Android Application Package (APK).
    These include permissions, API calls, URLs, components (activities, services, receivers, providers),
    manifest information (package name, version), and intent filters.
    """
    permissions: List[str]  # List of permissions requested by the app
    apis: List[str]  # List of API calls extracted from smali code
    urls: List[str]  # List of URLs found within the app's files
    components: Dict[str, List[str]]  # Dictionary mapping component types (e.g., 'activities') to lists of their names
    manifest_info: Dict[str, object]  # Key manifest information like package name, version code, version name
    intent_filters: Dict[str, List[Dict[str, List[str]]]] # Dictionary of intent filters declared by components

@dataclass
class BinaryFeatures:
    """
    Dataclass to hold features extracted from the binary analysis of an Android Application Package (APK).
    This includes sequences of API calls (from bytecode), raw strings found in the binary,
    and a summary of the application's call graph.
    """
    api_calls_sequences: List[List[str]]  # Sequences of API calls made by methods
    raw_strings: List[str]  # Raw strings extracted directly from the APK binary
    call_graph_summary: Dict[str, List[str]]  # A simplified representation of the app's call graph

@dataclass
class LLMDescriptions:
    """
    Dataclass to hold descriptions generated by a Large Language Model (LLM) based on extracted features.
    The 'by_feature' dictionary contains a summary or specific descriptions for various features.
    """
    by_feature: Dict[str, str]  # Dictionary mapping feature types to their LLM-generated descriptions

@dataclass
class ArtemisTensor:
    """
    Dataclass to hold the final tensor representations of static/binary features and LLM descriptions.
    These tensors are the input for the Convolutional Neural Network (CNN) model.
    """
    static_tensor: any  # Tensor representing static and binary features (e.g., encoded permissions, API call patterns)
    llm_tensor: any  # Tensor representing the LLM-generated descriptions (e.g., sentence embeddings)

@dataclass
class ClassificationResult:
    """
    Dataclass to hold the final classification outcome from the CNN model.
    Includes the predicted label (Benign/Malicious), confidence score,
    a boolean indicating if it's malicious, and any additional details.
    """
    label: str  # Predicted label (e.g., "Benign", "Malicious")
    confidence: float  # Confidence score of the prediction (0.0 to 1.0)
    is_malicious: bool  # Boolean flag: True if classified as malicious, False otherwise
    details: Dict[str, object]  # Additional details about the classification